export enum TokenRotationEvent {
  ROTATION_SUCCESS = 'ROTATION_SUCCESS',
  ROTATION_FAILED = 'ROTATION_FAILED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
};
