import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "node:path";

export default defineConfig({
  plugins: [react()],
  // Stubbed env vars for unit tests. The real values come from `.env.*` in
  // dev/build; tests just need *something* truthy so `assertEnv` doesn't
  // throw during module init (env.ts reads `import.meta.env` at top level).
  define: {
    "import.meta.env.VITE_API_BASE_URL": JSON.stringify(
      "http://localhost:3000",
    ),
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test-setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/test-setup.ts",
        "src/test-utils/**",
        "src/main.tsx",
        // Auto-generated RTK Query client — regenerated by `pnpm codegen`.
        "src/shared/api/ftsFunctionsApi.ts",
        // Hand-written codegen-substitute (see file header). The endpoints
        // are exercised through page tests, not directly here.
        "src/shared/api/authApi.ts",
        // App bootstrap — exercised by e2e, not unit tests.
        "src/app/**",
        "src/pages/**",
      ],
      // Set thresholds at the CURRENT achieved coverage to prevent regression.
      // Measured 2026-04-25 after the test-suite expansion (waves 1–4 of the
      // web-coverage initiative): lines 57.03%, branches 48.69%, functions
      // 54.27%, statements 56.25%. Floors are rounded *down* by ~2pt so
      // cosmetic noise doesn't flip CI. Raise as the test suite grows.
      // Re-measure with `pnpm --filter=@registry/web test:coverage`.
      thresholds: {
        lines: 55,
        functions: 52,
        branches: 46,
        statements: 54,
      },
    },
  },
  resolve: {
    alias: {
      src: path.resolve(__dirname, "./src"),
    },
  },
});
