-- AlterTable
ALTER TABLE `type` MODIFY `category` ENUM('FTS_CENTRALIZATION', 'FTS_FUNCTION_NAME', 'FTS_FUNCTION_STEP', 'FTS_FUNCTION_CATEGORY', 'FTS_FUNCTION_MARKER', 'FTS_FUNCTION_COMPLEXITY', 'FTS_FUNCTION_EXECUTION_FREQUENCY', 'WHO_PERFORMS_ACTION', 'FTS_FUNCTION_ACTION_TYPE', 'FTS_FUNCTION_EFFECTIVENESS', 'FTS_COMPETENCY_CENTER', 'FTS_DTI', 'FTS_FUNCTION_RELATION_TYPE', 'TECHNOLOGICAL_SOLUTION', 'FEEDBACK_SOURCE', 'FEEDBACK_QUALITY_METRICS', 'RESPONSIBLE', 'FTS_METHODOLOGY_STATUS', 'ACTION_STATUS') NOT NULL;

-- CreateTable
CREATE TABLE `actions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fts_function_detail_id` INTEGER NOT NULL,
    `status_id` INTEGER NOT NULL,
    `description` TEXT NOT NULL,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false,
    `deleted_at` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `actions` ADD CONSTRAINT `actions_fts_function_detail_id_fkey` FOREIGN KEY (`fts_function_detail_id`) REFERENCES `fts_function_details`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `actions` ADD CONSTRAINT `actions_status_id_fkey` FOREIGN KEY (`status_id`) REFERENCES `type`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
