-- AlterTable
ALTER TABLE `actions` ADD COLUMN `order` INTEGER NULL;

-- AlterTable
ALTER TABLE `types` MODIFY `category` ENUM('token_status', 'token_rotation_event', 'ACTION_HISTORY_TYPE', 'FTS_CENTRALIZATION', 'FTS_FUNCTION_NAME', 'FTS_FUNCTION_STEP', 'FTS_FUNCTION_CATEGORY', 'FTS_FUNCTION_MARKER', 'FTS_FUNCTION_COMPLEXITY', 'FTS_FUNCTION_EXECUTION_FREQUENCY', 'WHO_PERFORMS_ACTION', 'FTS_FUNCTION_ACTION_TYPE', 'FTS_FUNCTION_EFFECTIVENESS', 'FTS_COMPETENCY_CENTER', 'FTS_DTI', 'FTS_FUNCTION_RELATION_TYPE', 'TECHNOLOGICAL_SOLUTION', 'FEEDBACK_SOURCE', 'FEEDBACK_QUALITY_METRICS', 'FEEDBACK_ACCEPT_STATUS', 'RESPONSIBLE', 'FTS_METHODOLOGY_STATUS', 'ACTION_STATUS', 'PRIORITY_ACTION') NOT NULL;
